## Necessary imports

In [1]:
import numpy as np

from dojo.tree import ClassificationTree
from sklearn.datasets import load_iris

Exception: LIBSVM library not found.

## Loading data

In [2]:
iris = load_iris()
data = np.column_stack((iris["data"], iris["target"]))
np.random.shuffle(data)

X, y = data[:, :-1], data[:, -1]

train_size = int(150*0.7)
X_train, X_test, y_train, y_test = X[:train_size], X[train_size:], y[:train_size], y[train_size:]

## Building the model

In [3]:
tree = ClassificationTree()
tree.fit(X_train, y_train)

ClassificationTree(
    criterion='gini',
    max_depth=-1,
    root=<dojo.tree.utils.structure.Node object at 0x110fbfda0>,
)

In [4]:
tree

ClassificationTree(
    criterion='gini',
    max_depth=-1,
    root=<dojo.tree.utils.structure.Node object at 0x110fbfda0>,
)

## You can now easily visualize the tree itself with a simple call of a method!

In [5]:
tree.visualize()

 Is feature[3] >= 1.0?
 --> True:
   Is feature[3] >= 1.8?
   --> True:
     Prediction: 2.0
   --> False:
     Is feature[2] >= 5.6?
     --> True:
       Prediction: 2.0
     --> False:
       Prediction: 1.0
 --> False:
   Prediction: 0.0


## Let's predict some probabilities

In [6]:
tree.predict_proba(X_test)

array([array([1.]), array([0.02941176, 0.97058824]), array([1.]),
       array([0.94871795, 0.05128205]), array([1.]),
       array([0.02941176, 0.97058824]), array([0.02941176, 0.97058824]),
       array([1.]), array([1.]), array([0.02941176, 0.97058824]),
       array([1.]), array([1.]), array([0.94871795, 0.05128205]),
       array([1.]), array([0.94871795, 0.05128205]),
       array([0.94871795, 0.05128205]), array([0.02941176, 0.97058824]),
       array([1.]), array([0.94871795, 0.05128205]),
       array([0.94871795, 0.05128205]), array([1.]), array([1.]),
       array([0.02941176, 0.97058824]), array([1.]), array([1.]),
       array([0.94871795, 0.05128205]), array([0.94871795, 0.05128205]),
       array([0.02941176, 0.97058824]), array([1.]), array([1.]),
       array([0.94871795, 0.05128205]), array([0.94871795, 0.05128205]),
       array([0.94871795, 0.05128205]), array([0.02941176, 0.97058824]),
       array([1.]), array([1.]), array([1.]),
       array([0.94871795, 0.051282

## Evaluating the model

In [7]:
tree.evaluate(X_test, y_test)

Accuracy score: 0.9777777777777777


## AdaBoost

In [8]:
from dojo.ensemble import AdaBoostClassifier

In [9]:
adaboost = AdaBoostClassifier(base_classifier=ClassificationTree(), n_classifiers=20, verbose=True)
adaboost.fit(X_train, y_train)

----------------------------------
Iteration 1
Training classifier...
Classifier 1 trained.
Weighting missclassified samples...
Shuffling the data...
----------------------------------
Iteration 2
Training classifier...
Classifier 2 trained.
Weighting missclassified samples...
Shuffling the data...
----------------------------------
Iteration 3
Training classifier...
Classifier 3 trained.
Weighting missclassified samples...
Shuffling the data...
----------------------------------
Iteration 4
Training classifier...
Classifier 4 trained.
Weighting missclassified samples...
Shuffling the data...
----------------------------------
Iteration 5
Training classifier...
Classifier 5 trained.
Weighting missclassified samples...
Shuffling the data...
----------------------------------
Iteration 6
Training classifier...
Classifier 6 trained.
Weighting missclassified samples...
Shuffling the data...
----------------------------------
Iteration 7
Training classifier...
Classifier 7 trained.
Weightin

AdaBoostClassifier(
    base_classifier=ClassificationTree(
    criterion='gini',
    max_depth=-1,
    root=None,
),
    n_classifiers=20,
    verbose=True,
)

In [10]:
adaboost.evaluate(X_test, y_test)

Accuracy score: 0.9777777777777777
